### ISSUE TITLE
How to deploy the App in a k8s cluster

### ISSUE THREAD

**Issue by andybondar** [GubernatorNagibator/kubernetis#1]
## Assumptions

I assume here that GKE Kubernetes cluster is used for this task.

## Recommended repository structure and content
* `README.md` - to describe what is this project for
* Folder or file congaing the Application code (you're good here)
* `Dockerfile` congaing the instructions for `docker build` (you're good here as well)
* Folder congaing Kubernetes manifests (for example `k8s` folder)

## k8s objects

There are 3 k8s objects that we're going to create here:
* Namespace
* Deployment
* Service

## Namespace
Kubernetes Namespaces help to group different k8s objects that are belonged to the particular projects.
To create a namespace in your k8s cluster, run the following command:
```
kubectl apply -f nginx_ns.yaml
```

using this manifest:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
```

Alternatively, you can simply run this command:
```
kubectl create ns nginx
```
For more details on the `Namespace` object, please review the [documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/).

## Deployment
The `Deployment` is a *Controller* object for the *Pods*.  You define a *desired state* in a `Deployment`, and the `Deployment` changes the *actual state* to whatever *desired state* you defined. For example, you specified 1 replica in the *Deployment's* spec. Then, the replica (the Pod) gets deleted. The Deployment will start a new Pod.
For more details on the `Deployment` object, please review the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/).

To create the `Deploymemt`, run:
```
kubectl apply -f nginx_deploymemt.yaml
```
using the example manifest below:
<details>
<summary>nginx_deploymemt.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      restartPolicy: Always
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - name: nginx-http
          containerPort: 80
```

</details>

If the command succeeded, you should be able to see the following:
```
$ kubectl get pods -n nginx
NAME                               READY   STATUS    RESTARTS   AGE
nginx-deployment-575ffb6c5-j6m42   1/1     Running   0          9s
```

## Service
The `Pod` we created has an IP address:
```
$ kubectl get pods -n nginx -o wide
NAME                               READY   STATUS    RESTARTS   AGE     IP           NODE                                                  NOMINATED NODE   READINESS GATES
nginx-deployment-575ffb6c5-j6m42   1/1     Running   0          2m22s   10.16.0.12   gke-cpl-sta-l-gke-cluste-default-pool-4602ac95-455m   <none>           <none>
```
which means we can access the App using that IP. Well, we can do it from inside the cluster only, and it is no good if we want, for example, to access the App running in the Cloud, from our Desktop. Still, we can use the `kubectl port-forward` command:
```
kubectl port-forward pods/nginx-deployment-575ffb6c5-j6m42 8000:80 -n nginx
```
and then you can use this URL: http://127.0.0.1:8000

Of course, you cannot ask the users to run the `kubectl port-forward` command every time they want to access the App. But more importantly, Pods are the **ephemeral objects.** They get created and die all the time. And their IP addresses get changed. So you cannot relay on the Pod IPs. Also, you can have more than 1 replica under the Deployment, and in this case you need something to balance the requests. That's where the `Service` come to rescue! :)

Service is a permanent object. Simply put, in our case, the Service is used to expose the App to the external network:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
```
This specification creates a new Service object in the `nginx` namespace, named `nginx-svc`, which targets TCP port 80 on any Pod with the `app=nginx-app` label.

To create the `Service`, run:
```
kubectl apply -f nginx_svc.yaml
```

After a while, the following command will show the Service's **external IP:**
```
kubectl get svc -n nginx
NAME        TYPE           CLUSTER-IP    EXTERNAL-IP       PORT(S)        AGE
nginx-svc   LoadBalancer   10.20.8.186   104.198.135.212   80:32490/TCP   4m50s
```
Now, please pay attention to the following. Since you've specified the ` type: LoadBalancer` in the Service's spec, the Kubernetes cluster asked GCP to create the `Load Balances`, which is not the Kubernetes object, it is the GCP resource. In the GCP Web console, go to the **Network services -> Load balancing** to see it. This Load balancer actually does the job we mentioned earlier, it exposes the globally routable IP address and redirects the requests to the App's Pod(s).

Now you can use this URL to access the App:
http://104.198.135.212

Please keep in mind that in your case the IP will be different :)
